plugins:
    - remark-preset-lint-consistent
    - remark-preset-lint-recommended
    - - remark-mdx
      - printWidth: 60
    - remark-frontmatter
    - [remark-lint-maximum-line-length, 60]
    - remark-directive
